/bin/bash: /home/mts247/.conda/envs/rag/lib/libtinfo.so.6: no version information available (required by /bin/bash)
bash: /home/mts247/.conda/envs/rag/lib/libtinfo.so.6: no version information available (required by bash)
rm: cannot remove 'A100/*.csv': No such file or directory
rm: cannot remove 'our/*.csv': No such file or directory
rm: cannot remove '*.pdf': No such file or directory
A100 compute area: 583.9627524481152 mm2
A100 IO area: 242.80080253195476 mm2
A100 total area: 826.76355498007 mm2
Our compute area: 462.7983590220655 mm2
Our IO area: 323.78295829519465 mm2
Our total area: 786.5813173172601 mm2
1280
Traceback (most recent call last):
  File "/home/mts247/.conda/envs/llmcompass_ae/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/mts247/.conda/envs/llmcompass_ae/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/mts247/CSL-Research/LLM-Modeling/LLMCompass/ae/figure12/test_throughput.py", line 135, in <module>
    p.start()
  File "/home/mts247/.conda/envs/llmcompass_ae/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/mts247/.conda/envs/llmcompass_ae/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/mts247/.conda/envs/llmcompass_ae/lib/python3.9/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/mts247/.conda/envs/llmcompass_ae/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/mts247/.conda/envs/llmcompass_ae/lib/python3.9/multiprocessing/popen_fork.py", line 65, in _launch
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files
slurmstepd: error: *** JOB 4020156 ON sablab-gpu-01 CANCELLED AT 2024-06-08T17:52:06 ***
